require:
  - standard
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "bin/*"

RSpec:
  Enabled: true
